[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/la-methode-lca/a-acculer-les-puissants/index.html"
to = "/la-methode-lca/acculer/"

[[redirects]]
from = "/la-methode-lca/l-legitimer-les-pionniers/index.html"
to = "/la-methode-lca/legitimer/"

[[redirects]]
from = "/la-methode-lca/c-convertir-la-majorite/index.html"
to = "/la-methode-lca/convertir/"

